#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

red="\033[0;31m"
green="\033[0;32m"
yellow="\033[0;33m"
skyblue="\033[0;36m"
no_color="\033[0m"

# Format with prettier
echo -e "${skyblue} ===== Formating your code with prettier ===== ${no_color}";
npm run prettier-format ||
(
  echo -e "${red} Prettier Check Failed. ${no_color}
    Make changes and try commit again. \n";
  false;
)

# Format with eslint
echo -e "\n${skyblue} ===== Formating your code with eslint ===== ${no_color}";
npm run eslint-format ||
(
  echo -e "${red} ESLint Check Failed. ${no_color} 
    Make the required changes listed above, add changes and try to commit again. \n"
  false; 
)

# Check tsconfig standards
echo -e "\n${skyblue} ===== Type checking ===== ${no_color}";
npm run check-types ||
(
  echo -e  "${red} Failed Type check. ${no_color}
    Make the changes required above. \n"
  false;
)

# Run jest test
echo -e "\n${skyblue} ===== Unit testing ===== ${no_color}";
npm run test || (
  echo -e  "${red} Failed unit tests. ${no_color}
    Run 'npm run test' and fix the failing tests. \n"
  false;
)

# If everything passes... Now we can commit
echo -e "\n${skyblue} All checks passed. Attempting to build now... \n${no_color}"
npm run build ||
(
  echo -e "\n${red}Better call Bob... Because your build failed ${no_color}
    Next build failed: View the errors above to see why. \n"
  false;
)

# If everything passes... Now we can commit
echo -e  "\n${green} ✅✅✅✅ Everything looks good. Committing changes... ✅✅✅✅ \n${no_color}"